// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The widget subset used by an add-on.
public struct AddOnWidgetSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The list of widgets used in an add-on.
  public var usedWidgets: [AddOnWidgetSet.WidgetType] = []

  /// Initialize a new instance of `AddOnWidgetSet`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AddOnWidgetSet().with { $0.usedWidgets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The Widget type. DEFAULT is the basic widget set.
  public enum WidgetType: Codable, Equatable, Sendable {
    /// The default widget set.
    case unspecified
    /// The date picker.
    case datePicker
    /// Styled buttons include filled buttons and disabled buttons.
    case styledButtons
    /// Persistent forms allow persisting form values during actions.
    case persistentForms
    /// Fixed footer in card.
    case fixedFooter
    /// Update the subject and recipients of a draft.
    case updateSubjectAndRecipients
    /// The grid widget.
    case gridWidget
    /// A Gmail add-on action that applies to the addon compose UI.
    case addonComposeUiAction
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .datePicker: return 1
      case .styledButtons: return 2
      case .persistentForms: return 3
      case .fixedFooter: return 4
      case .updateSubjectAndRecipients: return 5
      case .gridWidget: return 6
      case .addonComposeUiAction: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WIDGET_TYPE_UNSPECIFIED"
      case .datePicker: return "DATE_PICKER"
      case .styledButtons: return "STYLED_BUTTONS"
      case .persistentForms: return "PERSISTENT_FORMS"
      case .fixedFooter: return "FIXED_FOOTER"
      case .updateSubjectAndRecipients: return "UPDATE_SUBJECT_AND_RECIPIENTS"
      case .gridWidget: return "GRID_WIDGET"
      case .addonComposeUiAction: return "ADDON_COMPOSE_UI_ACTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WidgetType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WIDGET_TYPE_UNSPECIFIED": self = .unspecified
      case "DATE_PICKER": self = .datePicker
      case "STYLED_BUTTONS": self = .styledButtons
      case "PERSISTENT_FORMS": self = .persistentForms
      case "FIXED_FOOTER": self = .fixedFooter
      case "UPDATE_SUBJECT_AND_RECIPIENTS": self = .updateSubjectAndRecipients
      case "GRID_WIDGET": self = .gridWidget
      case "ADDON_COMPOSE_UI_ACTION": self = .addonComposeUiAction
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WidgetType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .datePicker
      case 2: self = .styledButtons
      case 3: self = .persistentForms
      case 4: self = .fixedFooter
      case 5: self = .updateSubjectAndRecipients
      case 6: self = .gridWidget
      case 7: self = .addonComposeUiAction
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .datePicker: return try container.encode(1)
      case .styledButtons: return try container.encode(2)
      case .persistentForms: return try container.encode(3)
      case .fixedFooter: return try container.encode(4)
      case .updateSubjectAndRecipients: return try container.encode(5)
      case .gridWidget: return try container.encode(6)
      case .addonComposeUiAction: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.AddOnWidgetSet"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
