// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Add-on configuration that is shared across all add-on host applications.
public struct CommonAddOnManifest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The display name of the add-on.
  public var name: Swift.String = Swift.String()

  /// Required. The URL for the logo image shown in the add-on toolbar.
  public var logoUrl: Swift.String = Swift.String()

  /// Common layout properties for the add-on cards.
  public var layoutProperties: LayoutProperties? = nil

  /// The widgets used in the add-on. If this field is not specified,
  /// it indicates that default set is used.
  public var addOnWidgetSet: AddOnWidgetSet? = nil

  /// Whether to pass locale information from host app.
  public var useLocaleFromApp: Swift.Bool = Swift.Bool()

  /// Defines an endpoint that will be executed in any context, in
  /// any host. Any cards generated by this function will always be available to
  /// the user, but may be eclipsed by contextual content when this add-on
  /// declares more targeted triggers.
  public var homepageTrigger: HomepageExtensionPoint? = nil

  /// Defines a list of extension points in the universal action menu which
  /// serves as a setting menu for the add-on. The extension point can be
  /// link URL to open or an endpoint to execute as a form
  /// submission.
  public var universalActions: [UniversalActionExtensionPoint] = []

  /// An OpenLink action
  /// can only use a URL with an HTTPS, MAILTO or TEL scheme.  For HTTPS links,
  /// the URL must also
  /// [match](/gmail/add-ons/concepts/manifests#whitelisting_urls) one of the
  /// prefixes specified in this whitelist. If the prefix omits the scheme, HTTPS
  /// is assumed.  Notice that HTTP links are automatically rewritten to HTTPS
  /// links.
  public var openLinkUrlPrefixes: GoogleWKT.WKTListValue? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CommonAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CommonAddOnManifest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let logoUrl = CodingKeys(stringValue: "logoUrl")
    static let layoutProperties = CodingKeys(stringValue: "layoutProperties")
    static let addOnWidgetSet = CodingKeys(stringValue: "addOnWidgetSet")
    static let useLocaleFromApp = CodingKeys(stringValue: "useLocaleFromApp")
    static let homepageTrigger = CodingKeys(stringValue: "homepageTrigger")
    static let universalActions = CodingKeys(stringValue: "universalActions")
    static let openLinkUrlPrefixes = CodingKeys(stringValue: "openLinkUrlPrefixes")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "logoUrl",
      "layoutProperties",
      "addOnWidgetSet",
      "useLocaleFromApp",
      "homepageTrigger",
      "universalActions",
      "openLinkUrlPrefixes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logoUrl) {
      self.logoUrl = value
    }
    self.layoutProperties = try container.decodeIfPresent(
      LayoutProperties.self, forKey: .layoutProperties)
    self.addOnWidgetSet = try container.decodeIfPresent(
      AddOnWidgetSet.self, forKey: .addOnWidgetSet)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useLocaleFromApp) {
      self.useLocaleFromApp = value
    }
    self.homepageTrigger = try container.decodeIfPresent(
      HomepageExtensionPoint.self, forKey: .homepageTrigger)
    if let value = try container.decodeIfPresent(
      [UniversalActionExtensionPoint].self, forKey: .universalActions)
    {
      self.universalActions = value
    }
    self.openLinkUrlPrefixes = try container.decodeIfPresent(
      GoogleWKT.WKTListValue.self, forKey: .openLinkUrlPrefixes)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.logoUrl, forKey: .logoUrl)
    try container.encodeIfPresent(self.layoutProperties, forKey: .layoutProperties)
    try container.encodeIfPresent(self.addOnWidgetSet, forKey: .addOnWidgetSet)
    try container.encode(self.useLocaleFromApp, forKey: .useLocaleFromApp)
    try container.encodeIfPresent(self.homepageTrigger, forKey: .homepageTrigger)
    try container.encode(self.universalActions, forKey: .universalActions)
    try container.encodeIfPresent(self.openLinkUrlPrefixes, forKey: .openLinkUrlPrefixes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.CommonAddOnManifest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
