// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Add-on configuration that is shared across all add-on host applications.
public struct CommonAddOnManifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The display name of the add-on.
  public var name: Swift.String = Swift.String()

  /// Required. The URL for the logo image shown in the add-on toolbar.
  public var logoUrl: Swift.String = Swift.String()

  /// Common layout properties for the add-on cards.
  public var layoutProperties: LayoutProperties? = nil

  /// The widgets used in the add-on. If this field is not specified,
  /// it indicates that default set is used.
  public var addOnWidgetSet: AddOnWidgetSet? = nil

  /// Whether to pass locale information from host app.
  public var useLocaleFromApp: Swift.Bool = Swift.Bool()

  /// Defines an endpoint that will be executed in any context, in
  /// any host. Any cards generated by this function will always be available to
  /// the user, but may be eclipsed by contextual content when this add-on
  /// declares more targeted triggers.
  public var homepageTrigger: HomepageExtensionPoint? = nil

  /// Defines a list of extension points in the universal action menu which
  /// serves as a setting menu for the add-on. The extension point can be
  /// link URL to open or an endpoint to execute as a form
  /// submission.
  public var universalActions: [UniversalActionExtensionPoint] = []

  /// An OpenLink action
  /// can only use a URL with an HTTPS, MAILTO or TEL scheme.  For HTTPS links,
  /// the URL must also
  /// [match](/gmail/add-ons/concepts/manifests#whitelisting_urls) one of the
  /// prefixes specified in this whitelist. If the prefix omits the scheme, HTTPS
  /// is assumed.  Notice that HTTP links are automatically rewritten to HTTPS
  /// links.
  public var openLinkUrlPrefixes: GoogleCloudWkt.ListValue? = nil

  /// Initialize a new instance of `CommonAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CommonAddOnManifest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.CommonAddOnManifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
