// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Card layout properties shared across all add-on host applications.
public struct LayoutProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The primary color of the add-on. It sets the color of toolbar. If no
  /// primary color is set explicitly, the default value provided by the
  /// framework is used.
  public var primaryColor: Swift.String = Swift.String()

  /// The secondary color of the add-on. It sets the color of buttons.
  /// If primary color is set but no secondary color is set, the
  /// secondary color is the same as the primary color. If neither primary
  /// color nor secondary color is set, the default value provided by the
  /// framework is used.
  public var secondaryColor: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LayoutProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LayoutProperties().with { $0.primaryColor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let primaryColor = CodingKeys(stringValue: "primaryColor")
    static let secondaryColor = CodingKeys(stringValue: "secondaryColor")

    static let _knownKeys: Set<Swift.String> = [
      "primaryColor",
      "secondaryColor",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primaryColor) {
      self.primaryColor = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryColor) {
      self.secondaryColor = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.primaryColor, forKey: .primaryColor)
    try container.encode(self.secondaryColor, forKey: .secondaryColor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.LayoutProperties"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
