// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Format for declaring a universal action menu item extension point.
public struct UniversalActionExtensionPoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. User-visible text describing the action taken by activating this
  /// extension point, for example, "Add a new contact".
  public var label: Swift.String = Swift.String()

  /// Required. The action type supported on a universal action menu item. It
  /// could be either a link to open or an endpoint to execute.
  public var actionType: OneOf_ActionType? = nil

  /// Initialize a new instance of `UniversalActionExtensionPoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UniversalActionExtensionPoint().with { $0.label = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case label = "label"
    case openLink = "openLink"
    case runFunction = "runFunction"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.label = try container.decode(Swift.String.self, forKey: .label)

    var actionType: OneOf_ActionType? = nil
    let actionTypeCheckAndSet = {
      if actionType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'actionType'"))
      }
      actionType = $0
    }
    if let openLink = try container.decodeIfPresent(Swift.String.self, forKey: .openLink) {
      try actionTypeCheckAndSet(.openLink(openLink))
    }
    if let runFunction = try container.decodeIfPresent(Swift.String.self, forKey: .runFunction) {
      try actionTypeCheckAndSet(.runFunction(runFunction))
    }
    self.actionType = actionType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.label, forKey: .label)

    if let choice = self.actionType {
      switch choice {
      case .openLink(let value):
        try container.encode(value, forKey: .openLink)
      case .runFunction(let value):
        try container.encode(value, forKey: .runFunction)
      }
    }
  }

  /// Required. The action type supported on a universal action menu item. It
  /// could be either a link to open or an endpoint to execute.
  public enum OneOf_ActionType: Codable, Equatable, Sendable {
    /// URL to be opened by the UniversalAction.
    case openLink(Swift.String)
    /// Endpoint to be run by the UniversalAction.
    case runFunction(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.UniversalActionExtensionPoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
